export const CANVAS_HEIGHT = 960;
export const CANVAS_WIDTH = 540;

export const COLORS = {
  BLACK: '#000000',
  BLUE: '#0000ff',
  BROWN: '#a52a2a',
  DARK_ORANGE: '#ff8c00',
  DARKER_ORANGE: '#f56042',
  GRAY: '#808080',
  GREEN: '#008000',
  LIGHT_BLUE: '#add8e6',
  LIGHT_BROWN: '#f4a460',
  LIGHT_GREEN: '#90ee90',
  LIGHT_ORANGE: '#ffcccb',
  LIGHT_PINK: '#ffb6c1',
  LIGHT_PURPLE: '#e6e6fa',
  LIGHT_YELLOW: '#ffffe0',
  OFF_WHITE: '#f5f5f5',
  ORANGE: '#ffa500',
  PINK: '#ffc0cb',
  PURPLE: '#800080',
  RED: '#ff0000',
  TRANSPARENT: 'transparent',
  TURQUOISE: '#40e0d0',
  WHITE: '#ffffff',
  YELLOW: '#ffff00',
};

export const EMOJIS = {
  ANGRY: '😡',
  BRONZE_MEDAL: '🥉',
  CROWN: '🫅',
  CRYING: '😢',
  FEARFUL: '😨',
  GOLD_MEDAL: '🥇',
  HAPPY: '😊',
  JOYFUL: '😂',
  NEUTRAL: '😐',
  PARTY: '🥳',
  SAD: '😔',
  SILVER_MEDAL: '🥈',
  SLEEPY: '😴',
  SMILE: '🙂',
  SURPRISED: '😲',
};
